
version: '2'

services:
  v2ray:
    image: rico93/v2ray_v3:go_pay
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: 'https://ssrgood.com'
      key: 'tuzi'
      docker: "true"
      speedtest: 6
      node_id: 8
      api_port: 2333
      downWithPanel: 1
      LDNS: 'localhost'
      TZ: "Asia/Shanghai"
      MYSQLHOST:
      MYSQLDBNAME:
      MYSQLUSR:
      MYSQLPASSWD:
      MYSQLPORT:
      PANELTYPE: 0
      usemysql: 0
      CF_Key: 
      CF_Email: 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: rico93/v2ray_v3:caddy
    restart: always
    environment:
      - ACME_AGREE=true
#      if u want to use cloudflare (for DNS challenge authentication)
      - CLOUDFLARE_EMAIL=
      - CLOUDFLARE_API_KEY=
      - V2RAY_DOMAIN=123123
      - V2RAY_PATH=/v2ray
      - V2RAY_EMAIL=dmxiaowu@outlook.com
      - V2RAY_PORT=10550
      - V2RAY_OUTSIDE_PORT=443
    network_mode: "host"
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
